site_name: wndr23
site_description: Estudiante apasionado por el desarrollo backend en Java y la ciberseguridad. CTF write-ups, notas de Spring Framework, y mÃ¡s.
site_author: wonderiing (wndr23)
site_url: https://wndr23.vercel.app/

# Repository
repo_name: wonderiing/Vault
repo_url: https://github.com/wonderiing/Vault

# Theme Configuration
theme:
  name: material
  language: es
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  palette:
    scheme: slate
    primary: black
    accent: purple
  
  features:
    - navigation.instant      # Instant loading
    - navigation.tracking     # URL tracking
    - navigation.sections     # Navigation sections
    # - navigation.expand       # Expand navigation by default
    - navigation.top          # Back to top button
    - search.suggest          # Search suggestions
    - search.highlight        # Highlight search results
    - search.share            # Share search results
    - content.code.copy       # Copy code button
    - content.code.annotate   # Code annotations
  
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

# Plugins
plugins:
  - search:
      lang: es
  - glightbox:  # Image lightbox
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: monokai
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra
extra:
  analytics:
    provider: google
    property: G-89PJFHK1T1
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wonderiing/CTFs-WriteUps
  generator: false

# Navigation
nav:
  - Home: index.md
  - CTFs:
    - ðŸš© HackTheBox:
      - Inicio: HackTheBox/index.md
      - Maquina Cap: HackTheBox/01-Maquina Cap.md
      - Maquina GetSimple: HackTheBox/02-GetSimple HackTheBox Academy Machine.md
      - Maquina Lame: HackTheBox/04-Maquina Lame.md
      - Maquina Jerry: HackTheBox/05-Maquina Jerry.md
      - Maquina Sau: HackTheBox/06-Maquina Sau.md
      - Maquina GoodGames: HackTheBox/07-Maquina GoodGames.md
      - Maquina Devvortex: HackTheBox/08-Maquina Devvortex.md
      - Maquina Precious: HackTheBox/09-Maquina Precious.md
      - Maquina Nibbles: HackTheBox/10-Maquina Nibbles.md
      - Maquina Busqueda: HackTheBox/11-Maquina Busqueda.md
      - Maquina BoardLight: HackTheBox/12-Maquina BoardLight.md
      - Maquina Editor: HackTheBox/13-Maquina Editor.md
      - Maquina Broker: HackTheBox/14-Maquina Broker.md
      - Maquina Titanic: HackTheBox/15-Maquina Titanic.md
      - Maquina Dog: HackTheBox/16-Maquina Dog.md
      - Maquina Editorial: HackTheBox/17-Maquina Editorial.md
      - Maquina Paper: HackTheBox/18-Maquina Paper.md
      - Maquina Devel: HackTheBox/19-Maquina Devel.md
      - Maquina LinkVortex: HackTheBox/20-Maquina LinkVortex.md
      - Maquina Cicada: HackTheBox/21-Maquina Cicada.md
      - Maquina Chemistry: HackTheBox/22-Maquina Chemistry.md
      - Maquina TwoMillion: HackTheBox/23-Maquina TwoMillion.md
      - Maqquina Alert: HackTheBox/24-Maquina Alert.md
      - Maquina Active: HackTheBox/25-Maquina Active.md
      - Maquina Forest: HackTheBox/26-Maquina Forest.md
      - Maquina Administrator: HackTheBox/27-Maquina Administrator.md
      - Maquina TombWatcher: HackTheBox/28-Maquina TombWatcher.md
      - Maquina VulnCicada: HackTheBox/29-Maquina VulnCicada.md
      - Maquina TimeLapse: HackTheBox/30-Maquina TimeLapse.md
      - Maquina Puppy: HackTheBox/31-Maquina Puppy.md
      - Maquina Certified: HackTheBox/33-Maquina Certified.md
      - Maquina Authority: HackTheBox/34-Maquina Authority.md
      - Maquina Fluffy: HackTheBox/35-Maquina Fluffy.md
      - Maquina Escape: HackTheBox/36-Maquina Escape.md
      - Maquina Baby: HackTheBox/37-Maquina Baby.md
      - Maquina EscapeTwo: HackTheBox/38-Maquina EscapeTwo.md
      - Maquina Support: HackTheBox/39-Maquina Support.md
      - Maquina Return: HackTheBox/40-Maquina Return.md
      - Maquina Manager: HackTheBox/41-Maquina Manager.md
    - ðŸš© DockerLabs:
      - Inicio: DockerLabs/index.md
      - Maquina Library: DockerLabs/03-Maquina Library DockerLabs.md
      - Maquina Psycho: DockerLabs/04-Maquina Psycho.md
      - Maquina File -- INCOMPLETA: DockerLabs/05-Maquina File.md
      - Maquina PequeÃ±as Mentirosas: DockerLabs/06-Maquina PequeÃ±as Mentirosas.md
      - Maquina Pntopntobarra: DockerLabs/07-Maquina Pntopntobarra.md
      - Maquina Amor: DockerLabs/09-Maquina Amor.md
      - Maquina Winterfell: DockerLabs/10-Maquina Winterfell.md
      - Maquina Pressenter: DockerLabs/11-Maquina Pressenter.md
      - Maquina Balulero: DockerLabs/12-Maquina Balulero.md
      - Maquina Vulnvault: DockerLabs/13-Maquina Vulnvault.md
      - Maquina Patriaquerida: DockerLabs/14-Maquina Patriaquerida.md
      - Maquina Mirame: DockerLabs/15-Maquina Mirame.md
      - Maquina Verdejo: DockerLabs/16-Maquina Verdejo.md
      - Maquina Allien: DockerLabs/17-Maquina Allien.md
      - Maquina Los 40 Ladrones: DockerLabs/18-Maquina Los 40 Ladrones.md
      - Maquina Extraviado: DockerLabs/19-Maquina Extraviado.md
      - Maquina Paradise: DockerLabs/21-Maquina Paradise.md
      - Maquina Dance Samba: DockerLabs/22-Maquina Dance Samba.md
      - Maquina Domain: DockerLabs/23-Maquina Domain.md
      - Maquina Backend: DockerLabs/24-Maquina Backend.md
      - Maquina LogisticCloud: DockerLabs/25-Maquina LogisticCloud.md
    - ðŸš© HackMyVm:
      - Inicio: HackMyVm/index.md
      - Maquina Nexus: HackMyVm/01-Maquina Nexus.md
      - Maquina Sysadmin: HackMyVm/02-Maquina Sysadmin.md
      - Maquina Thirteen: HackMyVm/03-Maquina Thirteen.md
    - ðŸš© TheHackerLabs:
      - Inicio: TheHackerLabs/index.md
      - Maquina JaulaCon2025: TheHackerLabs/01-Maquina JaulaCon.md
      - Maquina Campana Feliz: TheHackerLabs/02-Maquina Campana Feliz.md
      - Maquina TheFirstAvenger: TheHackerLabs/03-Maquina TheFirstAvenger.md
      - Maquina Cyberpunk: TheHackerLabs/04-Maquina Cyberpunk.md
      - Maquina PizzaHot: TheHackerLabs/05-Maquina PizzaHot.md
      - Maquina LavaShop: TheHackerLabs/06-Maquina LavaShop.md

